name: Build

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - 'ksu-man'
      - 'ksu-susfs-man'

jobs:
  build_kernel:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target: [a70q] #, a70s]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          sudo apt update
          DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            curl zip unzip \
            git libssh-dev rsync libelf-dev dwarves libssl-dev \
            linux-modules-extra-$(uname -r) build-essential
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch ToolChain
        run: |
          export KERNEL_DIR="$(pwd)"
          mkdir -p "$KERNEL_DIR/../Prebuilts"
          git clone https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b $KERNEL_DIR/../Prebuilts/los-clang
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 $KERNEL_DIR/../Prebuilts/gcc64
          git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 $KERNEL_DIR/../Prebuilts/gcc32
          git clone https://android.googlesource.com/platform/prebuilts/gas/linux-x86 $KERNEL_DIR/../Prebuilts/gas/linux-x86
          git clone --depth=1 https://android.googlesource.com/platform/prebuilts/build-tools $KERNEL_DIR/../Prebuilts/build-tools

          cd "$KERNEL_DIR"

      - name: Fetch AnyKernel3
        run: |
          export KERNEL_DIR="$(pwd)"
          git clone --branch master https://github.com/DerGoogler/AnyKernel3-A70-KSU_Next.git $KERNEL_DIR/../AnyKernel3
          mkdir $KERNEL_DIR/../files

      - name: Fetch SUSFS for KernelSU
        run: |
          export KERNEL_DIR="$(pwd)"
          git clone --branch kernel-4.14 https://gitlab.com/simonpunk/susfs4ksu.git $KERNEL_DIR/../susfs4ksu

      - name: Setup KSU
        run: |
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/refs/heads/next/kernel/setup.sh" | bash -

      - name: Setup SUSFS
        run: |
          export KERNEL_DIR="$(pwd)"
          export KERNEL_ROOT="$KERNEL_DIR/drivers"
          export SUS="$KERNEL_DIR/../susfs4ksu"
          
          cp $SUS/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch $KERNEL_DIR/KernelSU-Next/

          cp $SUS/kernel_patches/50_add_susfs_in_kernel-4.14.patch $KERNEL_DIR/
          cp $SUS/kernel_patches/fs/susfs.c $KERNEL_DIR/fs/
          cp $SUS/kernel_patches/include/linux/susfs.h $KERNEL_DIR/include/linux/

          cd $KERNEL_ROOT/KernelSU-Next

          patch -p1 < 10_enable_susfs_for_ksu.patch

      - name: Build Kernel With KSU
        run: |
          export KERNEL_DIR="$(pwd)"
          source ./build_kernel.sh ${{ matrix.target }}
          cp -r $KERNEL_DIR/../AnyKernel3/* $KERNEL_DIR/../files

      - name: Publish to GitHub
        id: release
        uses: softprops/action-gh-release@v2
        with:
          files: /home/runner/work/android_kernel_samsung_sm6150_KernelSU-Next/files/a70*
          name: KernelSU Next for A70
          tag_name: ${{ github.run_number }}
          body: |
            **Release Notes - Kernel**

            - **Kernel Version:** 4.14.190
            - **Clang Version:** Clang-r416183b

            :rocket: *Built with love by GitHub Actions.*
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
